# -*- coding: utf-8 -*-
"""sorting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1um4q2ZDUXT8w626SDUtVxEkfk6fDwCU_
"""

alphabets = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]

lists  = ["f", "h", "m", "i", "t", "o"]

# x is the particular value of a field in the list
# it is initialized as the default value 0 which represents "a" in the list 'alphabets'
x = 0

# a is the particular value of a field in the list
# it is initialized as the default value 0 which represents "f" in the list 'lists'
a = 0

lenght_of_lists = len(lists)
# As lenght of list starts from 0 the variable must be 1 less
lenght_of_lists = lenght_of_lists - 1

particular_alphabet_in_list_alphabets = alphabets[x]

particular_alphabet_in_list_lists = lists[a]

for particular_alphabet_in_list_alphabets in particular_alphabet_in_list_lists:
  if particular_alphabet_in_list_alphabets == particular_alphabet_in_list_lists:
    break
  else:
    x = x + 1
print("found : ", particular_alphabet_in_list_alphabets)

print("Lenght of list 'List' =  ", lenght_of_lists)


# while a == lenght_of_lists:
#   for particular_alphabet_in_list_alphabets in particular_alphabet_in_list_lists:
#     if particular_alphabet_in_list_alphabets == particular_alphabet_in_list_lists:
#       print("Found:- ", particular_alphabet_in_list_lists)
#       break
#     else:
#       x = x + 1
#   print("found : ", particular_alphabet_in_list_lists)
#   a = a + 1

while (a<=lenght_of_lists):
  for particular_alphabet_in_list_lists in particular_alphabet_in_list_alphabets:
    if particular_alphabet_in_list_lists == particular_alphabet_in_list_alphabets:
      print("hello", particular_alphabet_in_list_alphabets)
      break
    else:
      print("found", particular_alphabet_in_list_lists)
      x = x + 1
  a = a + 1
  print(particular_alphabet_in_list_lists)

alphabets = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", 
             "A", "B", "C", "D", "E", "F", "G", "G", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

lists  = ["f", "h", "m", "i", "t", "o", "T", "M"]
x = 0
a = 0


lenght_of_lists = len(lists)
lenght_of_lists = lenght_of_lists - 1


while (a<=lenght_of_lists):
  for alphabets[x] in lists[a]:
    if alphabets[x] == lists[a]:
      break
    else:
      x = x + 1
  print("found : ", alphabets[x])
  a = a + 1

print("Lenght of list 'List' =  ", lenght_of_lists)

alphabets = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", 
             "A", "B", "C", "D", "E", "F", "G", "G", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

lists  = ["f", "h", "m", "i", "t", "o", "T", "M"]
x = 0
a = 0


lenght_of_lists = len(lists)
lenght_of_lists = lenght_of_lists - 1
print(len(alphabets[3]))

while (a<=lenght_of_lists):
  for alphabets[x] in lists[a]:
    if alphabets[x] == lists[a]:
      break
    else:
      x = x + 1
  print("found : ", alphabets[x])
  a = a + 1

print("Lenght of list 'List' =  ", lenght_of_lists)